services:
  db:
    extends:
      service: db
      file: docker-compose.yml
    volumes:
      - ./gb_api_db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mariadb -uroot -p$MARIADB_ROOT_PASSWORD $MARIADB_API_DUMP_DATABASE -e 'SELECT 1 FROM wiki_accessory WHERE mw_page_name IS NOT NULL LIMIT 1;'"
      interval: 5s
      retries: 10
      start_period: 240s

  wiki:
    build:
      context: .
      args:
        INSTALL_API: "true"
    extends:
      service: wiki
      file: docker-compose.yml
    volumes:
      - ./gb_api_scripts:/var/www/html/maintenance/gb_api_scripts
